# Generated by Django 6.0.8 on 2026-08-06 03:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialNavegacion',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('sesion_id', models.CharField(default='', max_length=100)),
                ('fecha_visita', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='historial_navegacion', to='produccion.productoterminado')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='historial_navegacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_navegacion',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(default='', max_length=20, unique=True)),
                ('fecha_pedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('confirmado', 'confirmado'), ('en_proceso', 'en_proceso'), ('listo', 'listo'), ('enviado', 'enviado'), ('entregado', 'entregado'), ('cancelado', 'cancelado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia'), ('paypal', 'paypal'), ('tarjeta', 'tarjeta'), ('datafono', 'datafono')], default='efectivo', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'pendiente'), ('pagado', 'pagado'), ('parcial', 'parcial'), ('fallido', 'fallido'), ('reembolsado', 'reembolsado')], default='pendiente', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(default='')),
                ('direccion_envio', models.TextField(default='')),
                ('contacto_envio', models.CharField(default='', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('transferencia', 'transferencia'), ('paypal', 'paypal'), ('tarjeta', 'tarjeta'), ('datafono', 'datafono')], default='efectivo', max_length=20)),
                ('referencia', models.CharField(default='', max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('confirmado', 'confirmado'), ('pendiente', 'pendiente'), ('fallido', 'fallido'), ('reembolsado', 'reembolsado')], default='pendiente', max_length=20)),
                ('comprobante_url', models.CharField(default='', max_length=255)),
                ('observaciones', models.TextField(default='')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.pedido')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(default='')),
                ('ciudad', models.CharField(default='', max_length=50)),
                ('telefono_contacto', models.CharField(default='', max_length=20)),
                ('tipo_envio', models.CharField(choices=[('retiro', 'retiro'), ('domicilio', 'domicilio'), ('correo', 'correo'), ('mensajeria', 'mensajeria')], default='domicilio', max_length=20)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_envio', models.DateField(default=datetime.date.today)),
                ('fecha_entrega_estimada', models.DateField(default=datetime.date.today)),
                ('fecha_entrega_real', models.DateField(default=datetime.date.today)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('enviado', 'enviado'), ('entregado', 'entregado'), ('cancelado', 'cancelado'), ('devuelto', 'devuelto')], default='pendiente', max_length=20)),
                ('tracking_number', models.CharField(default='', max_length=100)),
                ('observaciones', models.TextField(default='')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='ventas.pedido')),
            ],
            options={
                'db_table': 'envio',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tipo_venta', models.CharField(choices=[('online', 'online'), ('presencial', 'presencial'), ('whatsapp', 'whatsapp'), ('instagram', 'instagram')], default='online', max_length=20)),
                ('vendedor', models.CharField(default='', max_length=100)),
                ('canal_venta', models.CharField(default='', max_length=50)),
                ('observaciones', models.TextField(default='')),
                ('activo', models.BooleanField(default=True)),
                ('id_pedido', models.OneToOneField(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='ventas.pedido')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_venta', to='produccion.productoterminado')),
                ('id_venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.RESTRICT, related_name='carrito', to='produccion.productoterminado')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='ventas.pedido')),
            ],
            options={
                'db_table': 'carrito',
                'constraints': [models.UniqueConstraint(fields=('id_pedido', 'id_producto'), name='uq_carrito_pedido_producto')],
            },
        ),
    ]
