# Generated by Django 6.0.8 on 2026-08-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
