# Generated by Django 6.0.8 on 2026-08-06 03:12

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseProduccion',
            fields=[
                ('id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(default='')),
                ('orden_secuencia', models.IntegerField(unique=True)),
                ('tiempo_estimado_minutos', models.IntegerField(default=30)),
                ('requiere_control_calidad', models.BooleanField(default=False)),
                ('requiere_insumos_especificos', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fase_produccion',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(default='', max_length=20, unique=True)),
                ('cantidad_producir', models.IntegerField()),
                ('cantidad_producida', models.IntegerField(default=0)),
                ('fecha_programada', models.DateField(default=datetime.date.today)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('planificada', 'planificada'), ('en_proceso', 'en_proceso'), ('completada', 'completada'), ('cancelada', 'cancelada'), ('pausada', 'pausada')], default='planificada', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'baja'), ('normal', 'normal'), ('alta', 'alta'), ('urgente', 'urgente')], default='normal', max_length=20)),
                ('responsable', models.CharField(default='', max_length=100)),
                ('observaciones', models.TextField(default='')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'orden_produccion',
            },
        ),
        migrations.CreateModel(
            name='ProductoTerminado',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_producto', models.CharField(default='', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
                ('aroma', models.CharField(choices=[('lavanda', 'lavanda'), ('limon', 'limon'), ('canela', 'canela'), ('coco', 'coco'), ('vainilla', 'vainilla'), ('pino_silvestre', 'pino_silvestre'), ('manzanilla', 'manzanilla'), ('romero', 'romero'), ('rosa', 'rosa'), ('maracuya', 'maracuya'), ('naranja', 'naranja'), ('floral', 'floral'), ('manzana', 'manzana'), ('invictus', 'invictus'), ('dolce_gabanna', 'dolce_gabanna'), ('kaiak_citrico', 'kaiak_citrico'), ('kaiak_aero', 'kaiak_aero'), ('jockey_club', 'jockey_club'), ('arroz', 'arroz'), ('avena', 'avena')], default='lavanda', max_length=30)),
                ('color', models.CharField(choices=[('rosado_princesa', 'rosado_princesa'), ('oro_viejo', 'oro_viejo'), ('rojo_navidad', 'rojo_navidad'), ('rojo_bandera', 'rojo_bandera'), ('rojo_num40', 'rojo_num40'), ('verde_navidad', 'verde_navidad'), ('verde_manzana', 'verde_manzana'), ('verde_menta_vegetal', 'verde_menta_vegetal'), ('green_num12', 'green_num12'), ('azul_uva_vegetal', 'azul_uva_vegetal'), ('violeta', 'violeta'), ('celeste', 'celeste'), ('negro', 'negro'), ('amarillo5_vegetal', 'amarillo5_vegetal'), ('anaranjado_vegetal', 'anaranjado_vegetal')], default='rosado_princesa', max_length=30)),
                ('peso', models.CharField(choices=[('100g', '100g'), ('75g', '75g'), ('50g', '50g'), ('kit_animalito_75g', 'kit_animalito_75g'), ('kit_piecito_60gr', 'kit_piecito_60gr'), ('kit_huellita_75g', 'kit_huellita_75g')], max_length=30)),
                ('tipo', models.CharField(choices=[('jabon', 'jabon'), ('kit', 'kit'), ('promocion', 'promocion'), ('muestra', 'muestra')], default='jabon', max_length=20)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('stock_reservado', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=10)),
                ('stock_maximo', models.IntegerField(default=100)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_resenas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'producto_terminado',
            },
        ),
        migrations.CreateModel(
            name='DetalleProduccion',
            fields=[
                ('id_detalle_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_requerida', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('cantidad_usada', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('lote_usado', models.CharField(default='', max_length=50)),
                ('costo_insumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField(default='')),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_produccion', to='inventario.materiaprima')),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'detalle_produccion',
            },
        ),
        migrations.CreateModel(
            name='DetalleFaseProduccion',
            fields=[
                ('id_detalle_fase', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('en_proceso', 'en_proceso'), ('completada', 'completada'), ('pausada', 'pausada'), ('cancelada', 'cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(default='')),
                ('tiempo_real_minutos', models.IntegerField(default=0)),
                ('incidencias', models.TextField(default='')),
                ('id_fase', models.ForeignKey(db_column='id_fase', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_fase', to='produccion.faseproduccion')),
                ('id_orden_produccion', models.ForeignKey(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_fase', to='produccion.ordenproduccion')),
            ],
            options={
                'db_table': 'detalle_fase_produccion',
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='produccion.productoterminado'),
        ),
        migrations.CreateModel(
            name='MermaProduccion',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_merma', models.CharField(choices=[('insumo', 'insumo'), ('producto', 'producto'), ('material_empaque', 'material_empaque')], max_length=30)),
                ('cantidad_perdida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(default='', max_length=20)),
                ('motivo', models.CharField(choices=[('calidad', 'calidad'), ('exceso', 'exceso'), ('derrame', 'derrame'), ('caducidad', 'caducidad'), ('defecto', 'defecto'), ('mal_manejo', 'mal_manejo')], max_length=50)),
                ('valor_perdido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('porcentaje_perdida', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por', models.CharField(default='', max_length=100)),
                ('observaciones', models.TextField(default='')),
                ('id_insumo', models.ForeignKey(blank=True, db_column='id_insumo', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mermas_produccion', to='inventario.materiaprima')),
                ('id_orden_produccion', models.ForeignKey(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='produccion.ordenproduccion')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mermas_produccion', to='produccion.productoterminado')),
            ],
            options={
                'db_table': 'merma_produccion',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoProduccion',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('lote_produccion', models.CharField(default='', max_length=50)),
                ('numero_orden', models.CharField(default='', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin_estimada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin_real', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado_actual', models.CharField(choices=[('planificada', 'planificada'), ('en_proceso', 'en_proceso'), ('completada', 'completada'), ('cancelada', 'cancelada'), ('pausada', 'pausada')], default='planificada', max_length=20)),
                ('fase_actual', models.CharField(default='', max_length=50)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('responsable_actual', models.CharField(default='', max_length=100)),
                ('observaciones_continuas', models.TextField(default='')),
                ('tiempo_total_estimado_minutos', models.IntegerField(default=0)),
                ('tiempo_total_real_minutos', models.IntegerField(default=0)),
                ('eficiencia_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cumplimiento_plazo', models.BooleanField(default=False)),
                ('calidad_aprobada', models.BooleanField(default=False)),
                ('fecha_control_calidad', models.DateTimeField(default=django.utils.timezone.now)),
                ('inspector_calidad', models.CharField(default='', max_length=100)),
                ('observaciones_calidad', models.TextField(default='')),
                ('id_orden_produccion', models.OneToOneField(db_column='id_orden_produccion', on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='produccion.ordenproduccion')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='produccion.productoterminado')),
            ],
            options={
                'db_table': 'seguimiento_produccion',
            },
        ),
        migrations.CreateModel(
            name='FormulaProducto',
            fields=[
                ('id_formula', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unidad', models.CharField(default='', max_length=20)),
                ('orden', models.IntegerField(default=1)),
                ('observaciones', models.TextField(default='')),
                ('activo', models.BooleanField(default=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, related_name='formulas', to='inventario.materiaprima')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='produccion.productoterminado')),
            ],
            options={
                'db_table': 'formula_producto',
                'constraints': [models.UniqueConstraint(fields=('id_producto', 'id_insumo'), name='uq_formula_producto_insumo')],
            },
        ),
    ]
