# Generated by Django 6.0.8 on 2026-08-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoterminado',
            name='aroma',
            field=models.CharField(choices=[('lavanda', 'lavanda'), ('limon', 'limon'), ('canela', 'canela'), ('coco', 'coco'), ('vainilla', 'vainilla'), ('pino_silvestre', 'pino_silvestre'), ('manzanilla', 'manzanilla'), ('romero', 'romero'), ('rosa', 'rosa'), ('maracuya', 'maracuya'), ('naranja', 'naranja'), ('floral', 'floral'), ('manzana', 'manzana'), ('invictus', 'invictus'), ('dolce_gabanna', 'dolce_gabanna'), ('jockey_club', 'jockey_club'), ('arroz', 'arroz'), ('avena', 'avena'), ('carbon_activo', 'carbon_activo'), ('matico', 'matico'), ('lumbre', 'lumbre')], default='lavanda', max_length=30),
        ),
    ]
