# Generated by Django 6.0.8 on 2026-08-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_alter_productoterminado_aroma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id_aroma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(default='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'aroma',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'color',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id_presentacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(default='')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'presentacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='aroma',
            field=models.ForeignKey(blank=True, db_column='id_aroma', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='produccion.aroma'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='color',
            field=models.ForeignKey(blank=True, db_column='id_color', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='produccion.color'),
        ),
        migrations.AlterField(
            model_name='productoterminado',
            name='peso',
            field=models.ForeignKey(blank=True, db_column='id_presentacion', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='produccion.presentacion'),
        ),
    ]
