# Generated by Django 6.0.8 on 2026-08-06 03:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMateria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('base', 'base'), ('aroma', 'aroma'), ('color', 'color'), ('aditivo', 'aditivo'), ('molde', 'molde'), ('empaque', 'empaque')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria_materia',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'tipo'), name='uq_categoria_nombre_tipo')],
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(choices=[('kg', 'kg'), ('gr', 'gr'), ('lt', 'lt'), ('ml', 'ml'), ('unidad', 'unidad')], max_length=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, related_name='materias_primas', to='inventario.categoriamateria')),
            ],
            options={
                'db_table': 'materia_prima',
            },
        ),
        migrations.CreateModel(
            name='MermaStock',
            fields=[
                ('id_merma_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_deteccion', models.DateField(auto_now_add=True)),
                ('responsable', models.CharField(max_length=100)),
                ('observaciones', models.TextField(default='')),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_procesamiento', models.DateField(default=datetime.date.today)),
                ('motivo', models.CharField(max_length=50)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, related_name='mermas_stock', to='inventario.materiaprima')),
            ],
            options={
                'db_table': 'merma_stock',
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'entrada'), ('salida', 'salida'), ('ajuste', 'ajuste'), ('transferencia', 'transferencia')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('compra', 'compra'), ('produccion', 'produccion'), ('venta', 'venta'), ('ajuste', 'ajuste'), ('perdida', 'perdida'), ('devolucion', 'devolucion'), ('inicial', 'inicial'), ('alerta', 'alerta')], max_length=20)),
                ('referencia_id', models.IntegerField(default=0)),
                ('referencia_tabla', models.CharField(default='', max_length=50)),
                ('observaciones', models.TextField(default='')),
                ('usuario_registro', models.CharField(default='', max_length=100)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='inventario.materiaprima')),
            ],
            options={
                'db_table': 'movimiento_stock',
            },
        ),
        migrations.CreateModel(
            name='StockMateriaPrima',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
                ('lote', models.CharField(max_length=50)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_reservada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ubicacion', models.CharField(default='', max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'disponible'), ('agotado', 'agotado'), ('vencido', 'vencido'), ('reservado', 'reservado')], default='disponible', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, related_name='stocks', to='inventario.materiaprima')),
            ],
            options={
                'db_table': 'stock_materia_prima',
                'constraints': [models.UniqueConstraint(fields=('id_insumo', 'lote'), name='uq_stock_insumo_lote')],
            },
        ),
    ]
