# Generated by Django 6.0.8 on 2026-08-06 03:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraMateriaPrima',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=50)),
                ('tipo_factura', models.CharField(choices=[('factura', 'factura'), ('recibo', 'recibo'), ('nota_venta', 'nota_venta'), ('boleta', 'boleta')], default='factura', max_length=20)),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
                ('fecha_recepcion', models.DateField(default=datetime.date.today)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('recibida', 'recibida'), ('cancelada', 'cancelada'), ('parcial', 'parcial')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(default='')),
                ('documento_url', models.CharField(default='', max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compra_materia_prima',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ruc_ci', models.CharField(default='', max_length=20, unique=True)),
                ('contacto', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=100)),
                ('direccion', models.TextField(default='')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('inactivo', 'inactivo')], default='activo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.CharField(default='', max_length=50)),
                ('fecha_vencimiento', models.DateField(default=datetime.date.today)),
                ('observaciones', models.TextField(default='')),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compramateriaprima')),
                ('id_insumo', models.ForeignKey(db_column='id_insumo', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_compra', to='inventario.materiaprima')),
            ],
            options={
                'db_table': 'detalle_compra',
            },
        ),
        migrations.AddField(
            model_name='compramateriaprima',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.RESTRICT, related_name='compras', to='compras.proveedor'),
        ),
        migrations.AddConstraint(
            model_name='compramateriaprima',
            constraint=models.UniqueConstraint(fields=('numero_factura',), name='uq_compra_materia_prima_numero_factura'),
        ),
    ]
