# Generated by Django 6.0.8 on 2026-08-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectStorage',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('clave_r2', models.CharField(max_length=255, unique=True)),
                ('url_publica', models.CharField(max_length=500)),
                ('grupo', models.CharField(blank=True, default='', max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo_contenido', models.CharField(blank=True, default='', max_length=100)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'objectstorage',
                'ordering': ['grupo', 'orden'],
            },
        ),
    ]
